name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: 'macos-latest'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: Build production project
        run: npm run build:prod
        if: always()
      - name: Lint typescript
        run: npm run lint:ts
        if: always()
      - name: Lint scss
        run: npm run lint:scss
        if: always()
      - name: Unit test
        run: npm run test:unit
        if: always()
      - name: Storybook build
        run: npm run storybook:build
        if: always()
      - name: Loki test
        run: npm run test:ui:ci


